### ISSUE TITLE
[PORT] Minecraft 1.21

### ISSUE THREAD

**Issue by zenfyrdev** [constellation-mc/andromeda#147]
### Tasks

- [x] Fix build errors [~36 + 8~, IDEA lied, 100 + 2]
- [x] Test all modules.

**Comment by zenfyrdev** [comment]
Status update: I keep fixing errors, but more keep popping up...

**Comment by zenfyrdev** [comment]
Modules to test:

- world
	- [x] world.auto_planting
	- [x] world.crop_temperature
	- [x] world.falling_beenests
	- [x] world.loot_barrels
	- [x] world.moist_control
	- [x] world.quick_fire
- blocks
	- [x] blocks.bed.power
	- [x] blocks.bed.safe
	- [x] blocks.bed.unsafe
	- [x] blocks.better_fletching_table
	- [x] blocks.cactus_bottle_filling
	- [x] blocks.campfire_effects
	- [x] blocks.falling_propagule
	- [x] blocks.guarded_loot
	- [x] blocks.incubator
- entities
	- [x] entities.bee_flower_duplication
	- [x] entities.better_furnace_minecart
	- [x] entities.boats
	- [x] entities.ghast_tweaks
	- [x] entities.minecart_speed_control
	- [x] entities.minecarts
	- [x] entities.slimes
	- [x] entities.snowball_tweaks
	- [x] entities.vehicle_unentrapment
	- [x] entities.villagers_follow_emeralds
	- [x] entities.zombie.all_pick_up
	- [x] entities.zombie.clean_pickup
- items
	- [x] items.balanced_mending
	- [x] items.better_names
	- [x] items.infinite_totem
	- [x] items.lava_disintegrator
	- [x] items.lockpick
	- [x] items.magnet
	- [x] items.minecart_block_picking
	- [x] items.pouches
	- [x] items.tooltips
- bugfixes
	- [x] bugfixes.advancement_shadow
- mechanics
	- [x] mechanics.dragon_fight
	- [x] mechanics.throwable_items
	- [x] mechanics.trading_goat_horn
	- [x] mechanics.villager_gifting
- gui
	- [x] gui.gui_particles
	- [x] gui.item_frame_tooltips
	- [x] gui.name_tooltips
	- [x] gui.no_more_adventure
	- [x] gui.smooth_tooltips
- misc
	- [x] misc.minor_inconvenience
	- [x] misc.recipe_advancements_generation
	- [x] misc.tiny_storage
	- [x] misc.translations
	- [x] misc.unknown
